services:
  - type: web
    name: pulsenetwork
    env: node
    plan: free
    autoDeploy: false
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
