services:
  - type: web
    name: pulsenetwork
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: pulsenetwork-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
